version: '2'

services:
  bokeh:
    restart: always
    build: .
    image: discover-tc-applicability:latest

    # Data is copied into the image at build time, so the following is not needed.
    # volumes:
    #  - './data:/project/discover-tc-applicability/data'

    ports:
      - '3251:5006'
